<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\codeMRI.Infrastructure\codeMRI.Infrastructure.csproj" />
    <ProjectReference Include="..\codeMRI.Core\codeMRI.Core.csproj" />
    <ProjectReference Include="..\codeMRI.Shared\codeMRI.Shared.csproj" />
  </ItemGroup>

</Project>
