using System.Collections.Generic;
using System.Threading.Tasks;

namespace codeMRI.Core.Interfaces;

/// <summary>
/// Service for generating vector embeddings from text content.
/// </summary>
public interface IEmbeddingService
{
    /// <summary>
    /// Generates a single embedding vector for the provided text.
    /// </summary>
    Task<float[]> GetEmbeddingAsync(string text);

    /// <summary>
    /// Generates multiple embedding vectors for a list of texts.
    /// </summary>
    Task<List<float[]>> GetEmbeddingsAsync(List<string> texts);

    /// <summary>
    /// Gets the dimension of the vectors generated by this service.
    /// </summary>
    int GetDimensions();

    /// <summary>
    /// Gets the name of the model being used for embeddings.
    /// </summary>
    string ModelName { get; }
}
